version: '3.3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=consultantsdb
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
        mysql:
             condition: service_completed_successfully
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_IMAGE_NAME}_app:${DOCKER_IMAGE_TAG}
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=consultantsdb
      - DB_PORT=3306
      - APP_PORT=8080
      - WAIT_HOSTS=mysql:3306
volumes:
  db: